export const DEFAULT_JOBS = [
  "Disclosure Day : XY025523, INT - DOOH Outdoor Campaign",
  "Disclosure Day : XY025729, UK - DOOH",
  "Disclosure Day : XY025732, UK - LSQ Digital",
  "Scary Movie 6 : XY025692, INT - DOOH Outdoor Campaign",
  "The Odyssey : XY025716, INT - DOOH Outdoor Campaign",
  "XYi Design House Job : XY014384, Showreel",
  "XYi Internal Use : XY016319, XYi - Time Off",
  "XYi Internal Use : XY020179, XYi - Training",
  "XYi Internal Use : XY025256, XYi - MAGI Marketing",
  "Angry Birds 3 Movie : XY025741, INT - Titles",
  "Better Man : XY022694, INT - Digital OV Mechs",
  "Bridget Jones Diary 25th Anniversary : XY025429, AUS - 1 SHEET - TEASER - PRINT - UPIM",
  "Bridget Jones Diary 25th Anniversary : XY025430, AUS - QUAD - PRINT - TEASER - UPIM",
  "By Any Means : XY025860, ITM Digital - Custom Lobby Display",
  "By Any Means : XY025877, ITM Print - Custom Lobby Display",
  "Children of Blood and Bone : XY025537, INT - Teaser Titles",
  "Cocomelon: The Movie : XY025855, INT - Titles",
  "Digger : XY025824, AUS - 1 SHEET - TEASER - PRINT - UPIM",
  "Disclosure Day : XY025153, AUS - Character 1 Sheets",
  "Disclosure Day : XY025290, UK - PRESS AD - Print",
  "Disclosure Day : XY025313, UK - INTH - QUAD",
  "Disclosure Day : XY025405, UK - INTH - LARGE FORMATS - VUE",
  "Disclosure Day : XY025421, AUS - 1 SHEET - PRINT - MAIN - UPIM",
  "Disclosure Day : XY025448, UK - On Screen Press Ad",
  "Disclosure Day : XY025490, INT - Outdoor Campaign Masters",
  "Disclosure Day : XY025492, INT - Outdoor Campaign",
  "Disclosure Day : XY025509, AUS - FOH - PRINT",
  "Disclosure Day : XY025526, IRE - PRESS AD - PRINT",
  "Disclosure Day : XY025529, Aus - Event Naming Rights",
  "Disclosure Day : XY025530, AUS - DOOH - EVENT",
  "Disclosure Day : XY025535, AUS - QUAD - PRINT - MAIN - UPIM",
  "Disclosure Day : XY025543, UK - Odeon Canvas - Round 2",
  "Disclosure Day : XY025545, UK - REGIONAL BESPOKES - PRINT",
  "Disclosure Day : XY025600, UK - OOH - T-SIDES",
  "Disclosure Day : XY025607, IRE - OOH",
  "Disclosure Day : XY025608, UK - DIGITAL - EXHIBITOR",
  "Disclosure Day : XY025610, NM - Digital - Packshots - Final Window",
  "Disclosure Day : XY025613, INT - Titles - Stacked",
  "Disclosure Day : XY025618, UK - OOH - 6 Sheets",
  "Disclosure Day : XY025622, UK - Digital Adapt",
  "Disclosure Day : XY025624, UK - Orbit Domination",
  "Disclosure Day : XY025626, AUS - DIGITAL - ONLINE",
  "Disclosure Day : XY025627, AUS - Crown Digi Screens",
  "Disclosure Day : XY025634, UK - INTH PANAFLEXES - PRINT",
  "Disclosure Day : XY025639, UK - OOH - London Underground",
  "Disclosure Day : XY025643, AUS - Email Footer",
  "Disclosure Day : XY025646, IRE - DOOH STATICS",
  "Disclosure Day : XY025647, UK - OOH - 96 SHEET",
  "Disclosure Day : XY025648, UK - OOH - MANCHESTER PICCADILLY",
  "Disclosure Day : XY025649, IRE - DOOH Motion",
  "Disclosure Day : XY025650, UK - Picturehouse Takeover",
  "Disclosure Day : XY025651, UK - CINEWORLD LSQ - PRINT",
  "Disclosure Day : XY025655, AUS - Squeeze Back",
  "Disclosure Day : XY025662, AUS - Split Audio",
  "Disclosure Day : XY025665, AUS - DIGITAL - DOOH",
  "Disclosure Day : XY025666, AUS - Pull Through",
  "Disclosure Day : XY025669, UK - Online",
  "Disclosure Day : XY025673, UK - Pub Quiz and Q&A Invite",
  "Disclosure Day : XY025676, UK - DIGITAL - MULTIMEDIA INVITE",
  "Disclosure Day : XY025678, UK - CW Book To Win",
  "Disclosure Day : XY025689, AUS - Premiere Art",
  "Disclosure Day : XY025694, UK - Curzon Soho",
  "Disclosure Day : XY025704, UK - OLLS Screen",
  "Disclosure Day : XY025711, AUS - Sydney Media Wall",
  "Disclosure Day : XY025715, UK - D96",
  "Disclosure Day : XY025727, UK - OOH - CROMINATION",
  "Disclosure Day : XY025730, UK - Screening Holding Slide",
  "Disclosure Day : XY025733, IRE - Premiere Invite",
  "Disclosure Day : XY025735, UK - Premiere Holding Slide",
  "Disclosure Day : XY025736, UK - INTH - Standee & Tent Card",
  "Disclosure Day : XY025760, UK - Bauer Static",
  "Disclosure Day : XY025762, IRE - Premiere Assets",
  "Disclosure Day : XY025766, AUS - PREMIERE ASSETS",
  "Disclosure Day : XY025769, UK - BSF Creative",
  "Disclosure Day : XY025772, IRE - Trade",
  "Disclosure Day : XY025778, Uk - PREMIERE ASSETS",
  "Disclosure Day : XY025780, UK - MM SCREENING ASSETS - PRINT",
  "Disclosure Day : XY025782, UK - MM Screening - Motion",
  "Disclosure Day : XY025788, AUS - DIGITAL - INSTAGRAM",
  "Disclosure Day : XY025790, UK - Odeon 70mm Digital",
  "Disclosure Day : XY025814, UK - BSF LSQ Placements",
  "Disclosure Day : XY025815, UK - DIGITAL - SOCIAL SKINS",
  "Disclosure Day : XY025880, UK - PRESS AD - Print",
  "Disclosure Day : XY025885, UK - Review Quote 4x5",
  "Finding Emily : XY025485, NM - Digital - Packshots - Final Window",
  "Finding Emily : XY025620, NM - Titles",
  "Focker In-Law : XY024810, INT - Titles",
  "Focker In-Law : XY025507, INT - Digital OV Mechs",
  "Focker In-Law : XY025522, INT - Print OV Mechs",
  "Forgotten Island : XY025165, INT - Print OV Masters",
  "Forgotten Island : XY025381, INT - Digital OV Masters",
  "Forgotten Island : XY025465, INT - Digital - Assets",
  "Forgotten Island : XY025474, AUS - 1 SHEET - TEASER - PRINT - UPIM",
  "Forgotten Island : XY025510, AUS - QUAD - PRINT - MAIN - UPIM",
  "Forgotten Island : XY025687, INT - Cine Europe",
  "Forgotten Island : XY025722, INT - 1 Sheet - Digital - Trio",
  "Forgotten Island : XY025723, INT - Digital - Instagram - Trio",
  "Forgotten Island : XY025724, INT - 1 Sheet - Print - Trio",
  "Forgotten Island : XY025726, UK - INTH Quad",
  "Forgotten Island : XY025761, INT - Cine Europe Photo Booth",
  "Forgotten Island : XY025804, INT - DOOH - FLIGHTCHECKING",
  "Forgotten Island : XY025808, INT - Standee",
  "Forgotten Island : XY025813, INT - Outdoor Campaign",
  "Forgotten Island : XY025835, UK - INTH PANAFLEXES - PRINT",
  "Forgotten Island : XY025836, UK - INTH - LARGE FORMATS - VUE",
  "Heart Of The Beast : XY025604, INT - Titles",
  "Heart Of The Beast : XY025841, INT - Digital OV Mechs",
  "Heart Of The Beast : XY025842, INT - Print OV Mechs",
  "Heart Of The Beast : XY025843, INT - Outdoor Campaign Masters",
  "Heart Of The Beast : XY025844, INT - Outdoor Campaign Markets",
  "Heart Of The Beast : XY025845, INT - Outdoor Campaign Bespokes",
  "Heart Of The Beast : XY025846, INT - Asset Chart",
  "Heart Of The Beast : XY025847, INT - Green Launch Digital Assets",
  "Heart Of The Beast : XY025849, INT - Teaser P1S",
  "Heart Of The Beast : XY025850, DOM - French Canada Assets",
  "Heart Of The Beast : XY025861, DOM - Outdoor Digital Billboards",
  "Heart Of The Beast : XY025876, GER Launch Assets",
  "Iron Maiden - Burning Ambition : XY025525, UK - Premiere Invite",
  "Jackass: Best and Last : XY025589, INT - Teaser Titles",
  "Jackass: Best and Last : XY025603, INT - Digital OV Mechs",
  "Jackass: Best and Last : XY025623, INT - Launch - French Canada Assets",
  "Jackass: Best and Last : XY025686, INT - Print OV Mechs",
  "Jackass: Best and Last : XY025709, DOM - Outdoor Digital Billboards",
  "Jackass: Best and Last : XY025719, INT - Outdoor Campaign Masters",
  "Jackass: Best and Last : XY025720, INT - Outdoor Campaign Markets",
  "Jackass: Best and Last : XY025721, INT - Outdoor Campaign Bespokes",
  "Jackass: Best and Last : XY025744, INT - Cart Digital Launch",
  "Jackass: Best and Last : XY025745, INT - Cart Print Launch",
  "Jackass: Best and Last : XY025746, INT - Outdoor Title Adjustment",
  "Jackass: Best and Last : XY025751, GER Launch Assets",
  "Jackass: Best and Last : XY025759, DOM CANFR Launch Assets",
  "Jackass: Best and Last : XY025774, ITM Digital - Custom Lobby Display",
  "Jackass: Best and Last : XY025776, AUS - Outdoor Campaign",
  "Jackass: Best and Last : XY025783, ITM Print - Custom Lobby Display",
  "Jackass: Best and Last : XY025789, DOM - Digital PLF Mechs",
  "Jackass: Best and Last : XY025791, DOM - Print - PLF",
  "Jackass: Best and Last : XY025803, INT - CMYK Conversion",
  "Jackass: Best and Last : XY025854, INT - DIGITAL - ENTERPRISE UPLOADS",
  "Jackass: Best and Last : XY025859, NZ - Digital Online",
  "KPOP Superstar : XY025561, INT - Teaser Titles",
  "Lorne : XY025679, NM - Digital - Packshots - Final Window",
  "Lorne : XY025797, NM - Titles",
  "Minions & Monsters : XY025094, INT - Titles",
  "Minions & Monsters : XY025283, AUS - Split Audio",
  "Minions & Monsters : XY025358, AUS - Toolkits",
  "Minions & Monsters : XY025642, AUS - Email Footer",
  "Minions & Monsters : XY025675, AUS - DIGITAL - ONLINE",
  "Minions & Monsters : XY025681, AUS - 1 SHEET - PRINT - MAIN - UPIM",
  "Minions & Monsters : XY025682, NM - Digital - Packshots - Final Window",
  "Minions & Monsters : XY025700, AUS - QUAD - PRINT - MAIN - UPIM",
  "Minions & Monsters : XY025705, AUS - Comic Con Social",
  "Minions & Monsters : XY025706, INT - Cine Europe",
  "Minions & Monsters : XY025810, AUS - Pull Through",
  "Minions & Monsters : XY025838, AUS - Premiere Dooh",
  "Minions The Rise Of Gru : XY016704, Cinepolis Presentation Mock-ups",
  "Not Alone : XY025853, INT - Titles",
  "Obsession : XY025451, NM - Digital - Packshots - EPO",
  "Obsession : XY025562, NM - Digital - Packshots - Final Window",
  "Obsession : XY025581, NM - Titles",
  "One Night Only : XY025701, AUS - QUAD - PRINT - TEASER - UPIM",
  "One Night Only : XY025708, INT - Cine Europe",
  "One Night Only : XY025869, NM - Digital - Packshots - Final Window",
  "One Night Only : XY025874, NM - Titles",
  "Passenger : XY025488, INT - Print OV Mechs",
  "Passenger : XY025521, INT - CMYK Conversion",
  "Paw Patrol: The Dino Movie : XY025368, INT - Digital OV Mechs",
  "Paw Patrol: The Dino Movie : XY025370, INT - Print OV Mechs",
  "Paw Patrol: The Dino Movie : XY025454, INT - Rock Launch Assets",
  "Paw Patrol: The Dino Movie : XY025476, GER Launch Assets",
  "Paw Patrol: The Dino Movie : XY025482, INT - Asset Chart",
  "Paw Patrol: The Dino Movie : XY025539, INT - DIGITAL - ENTERPRISE UPLOADS",
  "Paw Patrol: The Dino Movie : XY025742, INT - DIGITAL - PAN REGIONAL",
  "Paw Patrol: The Dino Movie : XY025775, ITM Digital - Custom Lobby Display",
  "Paw Patrol: The Dino Movie : XY025792, INT - Outdoor Campaign Masters",
  "Paw Patrol: The Dino Movie : XY025793, INT - Outdoor Campaign Markets",
  "Paw Patrol: The Dino Movie : XY025794, INT - Outdoor Campaign Bespokes",
  "Paw Patrol: The Dino Movie : XY025809, INT - Collage Digital Assets",
  "Paw Patrol: The Dino Movie : XY025820, INT - Character D1S",
  "Paw Patrol: The Dino Movie : XY025821, INT - Character Instagrams",
  "Paw Patrol: The Dino Movie : XY025822, INT - Character P1S",
  "Paw Patrol: The Dino Movie : XY025851, DOM - Outdoor Digital Billboards",
  "Paw Patrol: The Dino Movie : XY025864, INT - Print Payoff Quad Creation",
  "Paw Patrol: The Dino Movie : XY025868, ITM Print - Custom Lobby Display",
  "Paw Patrol: The Dino Movie : XY025871, INT - Prehistoric Launch Print Assets",
  "Pressure : XY025690, NM - Digital - Packshots - Final Window",
  "Scary Movie 6 : XY025382, INT - DIGITAL - ENTERPRISE UPLOADS",
  "Scary Movie 6 : XY025437, DOM - Outdoor Digital Billboards",
  "Scary Movie 6 : XY025587, INT - Print Teaser Quad Creation",
  "Scary Movie 6 : XY025635, INT - DIGITAL - PAN REGIONAL",
  "Scary Movie 6 : XY025641, INT - Theatre Art Finishing",
  "Scary Movie 6 : XY025671, DOM - Digital - AV_LOGO",
  "Scary Movie 6 : XY025684, AUS - Outdoor Campaign",
  "Scary Movie 6 : XY025697, INT - DOOH Outdoor Campaign - Bespoke",
  "Scary Movie 6 : XY025728, AUS - DOOH Campaign",
  "Shrek 25th Anniversary : XY025427, AUS - 1 SHEET - TEASER - PRINT - UPIM",
  "Shrek 5 : XY023362, INT - Titles",
  "Shrek 5 : XY023390, INT - Digital OV Masters",
  "Shrek 5 : XY023391, INT - Print OV Masters",
  "Shrek 5 : XY025707, INT - Cine Europe",
  "Sonic The Hedgehog 4 : XY025357, INT - Titles",
  "Street Fighter : XY025124, INT - Teaser Titles",
  "Street Fighter : XY025126, INT - Digital OV Mechs",
  "Street Fighter : XY025141, INT - DIGITAL - ENTERPRISE UPLOADS",
  "Street Fighter : XY025557, INT - Multiple Artwork Launch",
  "Street Fighter : XY025559, INT - Teaser Artwork Print One Sheet",
  "Street Fighter : XY025601, INT - Print OV Mechs",
  "Street Fighter : XY025657, ITM Digital - Custom Lobby Display",
  "Street Fighter : XY025812, INT - Creative Legendary Adapt",
  "Supergirl : XY025502, AUS - Split Audio",
  "Supergirl : XY025515, AUS - 1 SHEET - PRINT - MAIN - UPIM",
  "Supergirl : XY025516, AUS - QUAD - PRINT - MAIN - UPIM",
  "Supergirl : XY025527, AUS - DIGITAL - ONLINE",
  "Supergirl : XY025591, AUS - OOH - Mural",
  "Supergirl : XY025617, AUS - OOH",
  "Supergirl : XY025628, AUS - DOOH - HOYTS",
  "Supergirl : XY025629, AUS - DOOH - VILLAGE",
  "Supergirl : XY025630, Aus - Event Naming Rights",
  "Supergirl : XY025631, AUS - Hoyts Billboard",
  "Supergirl : XY025632, AUS - DOOH - EVENT",
  "Supergirl : XY025633, AUS - Hoyts Ident",
  "Supergirl : XY025644, AUS - Email Footer",
  "Supergirl : XY025737, AUS - Supanova",
  "Supergirl : XY025768, AUS - IMAX Signage",
  "Supergirl : XY025770, AUS - IMAX Light Projection",
  "Supergirl : XY025787, AUS - BLB DOOH",
  "Supergirl : XY025857, AUS - Premiere Dooh",
  "Supergirl : XY025858, AUS - Event HPTO",
  "Tad and the Magic Lamp : XY025781, INT - Titles",
  "Tad and the Magic Lamp : XY025829, INT - Digital OV Mechs",
  "Tad and the Magic Lamp : XY025830, INT - Print OV Mechs",
  "Tad and the Magic Lamp : XY025831, INT - Outdoor Campaign Masters",
  "Tad and the Magic Lamp : XY025832, INT - Outdoor Campaign Markets",
  "Tad and the Magic Lamp : XY025833, INT - Online Launch Assets",
  "Tad and the Magic Lamp : XY025834, INT - Print Launch Assets",
  "Tad and the Magic Lamp : XY025873, INT - Finishing",
  "The AI Doc Or How I Became An Apocaloptimist : XY025541, NM - Digital - Packshots - Final Window",
  "The AI Doc Or How I Became An Apocaloptimist : XY025577, NM - Titles",
  "The AI Doc Or How I Became An Apocaloptimist : XY025656, UK - Launch Assets",
  "The Comeback King : XY025517, INT - Print - Flightcheck",
  "The Comeback King : XY025531, AUS - Insta Localisations",
  "The Fast And The Furious: 25th Anniversary : XY025865, UK - Digital - Localisations",
  "The Fast And The Furious: 25th Anniversary : XY025866, UK - INTH - QUAD",
  "The Fast And The Furious: 25th Anniversary : XY025867, UK - Print 1 Sheet",
  "The Fast And The Furious: 25th Anniversary : XY025878, AUS - Digital 1 Sheets & Instagrams",
  "The Fast And The Furious: 25th Anniversary : XY025879, AUS - Trailer Localise",
  "The Holiday 20th Anninversary : XY025504, AUS - 1 SHEET - PRINT - MAIN - UPIM",
  "The Odyssey : XY023441, INT - Titles",
  "The Odyssey : XY023474, INT - Digital OV Masters",
  "The Odyssey : XY025116, INT - Outdoor Campaign Masters",
  "The Odyssey : XY025156, AUS - 1 SHEET - PRINT - MAIN - UPIM",
  "The Odyssey : XY025619, AUS - FOYER BOLLARDS",
  "The Odyssey : XY025654, AUS - 1 SHEET - PRINT - MAIN - UPIM",
  "The Odyssey : XY025658, UK - VUE LARGE FORMATS",
  "The Odyssey : XY025660, AUS - QUAD - PRINT - MAIN - UPIM",
  "The Odyssey : XY025661, UK - BFI Bespoke",
  "The Odyssey : XY025663, AUS - Split Audio",
  "The Odyssey : XY025667, UK - PRESS AD - Print",
  "The Odyssey : XY025668, UK - Science Museum Bespokes",
  "The Odyssey : XY025674, INT - Outdoor Campaign",
  "The Odyssey : XY025683, UK - INTH PANAFLEXES - PRINT",
  "The Odyssey : XY025685, AUS - Press Ad",
  "The Odyssey : XY025698, UK - Mockups",
  "The Odyssey : XY025699, UK - INTH - Odeon Canvas",
  "The Odyssey : XY025702, INT - Standee",
  "The Odyssey : XY025712, UK - Sky VIP Assets",
  "The Odyssey : XY025713, INT - Cine Europe",
  "The Odyssey : XY025714, UK - Premiere Invite",
  "The Odyssey : XY025717, INT - DOOH Outdoor Campaign - Masters",
  "The Odyssey : XY025725, UK - OOH - Bus Wrap",
  "The Odyssey : XY025731, UK - 6 Sheet and Tent Cards",
  "The Odyssey : XY025739, UK - OOH - Alpha Banner",
  "The Odyssey : XY025740, UK - OOH - Liverpool Holiday Inn",
  "The Odyssey : XY025747, AUS - Print - Banner",
  "The Odyssey : XY025748, UK - OOH - BIRMINGHAM ARCHWAY BANNER",
  "The Odyssey : XY025749, UK - Everyman Cover",
  "The Odyssey : XY025750, UK - 240 Sheet",
  "The Odyssey : XY025752, AUS - DOOH - HOYTS",
  "The Odyssey : XY025753, Aus - Event Naming Rights",
  "The Odyssey : XY025754, AUS - Event HPTO",
  "The Odyssey : XY025755, AUS - Hoyts Ident",
  "The Odyssey : XY025756, AUS - Hoyts Billboard",
  "The Odyssey : XY025757, AUS - DOOH - VILLAGE",
  "The Odyssey : XY025758, AUS - DOOH - EVENT",
  "The Odyssey : XY025764, AUS - INTH DOORS",
  "The Odyssey : XY025765, AUS - Postcard",
  "The Odyssey : XY025767, UK - Online",
  "The Odyssey : XY025771, UK - OOH - T-SIDES",
  "The Odyssey : XY025773, UK - OOH - IMAX Wrap",
  "The Odyssey : XY025777, UK - Everyman Gift Card",
  "The Odyssey : XY025779, IRE - OOH",
  "The Odyssey : XY025795, UK - DIGITAL - EXHIBITOR",
  "The Odyssey : XY025798, IRE - DOOH Motion",
  "The Odyssey : XY025799, IRE - Digital Skybridge",
  "The Odyssey : XY025800, IRE - PRESS AD",
  "The Odyssey : XY025801, UK - OOH - LUG 48 Sheet",
  "The Odyssey : XY025802, UK - CW LSQ Print",
  "The Odyssey : XY025805, UK - REGIONAL BESPOKES - PRINT",
  "The Odyssey : XY025807, UK - TOS Assets",
  "The Odyssey : XY025811, AUS - Online Campaign",
  "The Odyssey : XY025816, OOH - Glasgow Central Station Banner",
  "The Odyssey : XY025837, AUS - IMAX Signage",
  "The Odyssey : XY025839, UK - IMAX 6 Sheets",
  "The Odyssey : XY025840, AUS - Screening Assets",
  "The Odyssey : XY025852, UK - CW Book To Win",
  "The Odyssey : XY025856, INT - DOOH - Airport Affinity Takeovers",
  "The Odyssey : XY025862, AUS - Print - Magazine",
  "The Odyssey : XY025863, AUS - FOH - PRINT",
  "The Odyssey : XY025870, UK - Rotunda DOOH Masters",
  "The Odyssey : XY025872, AUS - QUAD - PRINT - MAIN - UPIM",
  "The Odyssey : XY025875, CineEurope 2026 - ODY - Coke Screen",
  "The Odyssey : XY025881, AUS - Press Ad",
  "The Odyssey : XY025882, AUS - PRINT - IMAX TAKEOVER",
  "The Odyssey : XY025883, UK - Premiere Tickets",
  "The Odyssey : XY025884, UK - INTH - QUAD",
  "The Odyssey : XY025886, UK - Picturehouse Takeover",
  "The Odyssey : XY025887, UK - Curzon Soho",
  "The Super Mario Galaxy Movie : XY025215, NM - Digital - Packshots - Final Window",
  "The Super Mario Galaxy Movie : XY025386, INTL - Digital - Media Banners - Boats",
  "The Super Mario Galaxy Movie : XY025406, IT - Digital - Web Banners",
  "The Super Mario Galaxy Movie : XY025738, UK - Half Term Exhibs",
  "XYi Design House Job : XY016893, XYi Brand Guidelines",
  "XYi Design House Job : XY017029, Territory Showreel Presentation",
  "XYi Design House Job : XY017030, XYi Presentation Templates",
  "XYi Design House Job : XY017031, Universal Credential Pitch",
  "XYi Design House Job : XY017078, Seasons Greetings",
  "XYi Design House Job : XY017137, XYI - SOCIAL CONTENT",
  "XYi Design House Job : XY019647, Christmas Card",
  "XYi Design House Job : XY022852, RC - Logo",
  "XYi Design House Job : XY023118, XYi - Internal Screens",
  "XYi Internal Use : XY016776, XYi - R&D and Training",
  "XYi Internal Use : XY016914, Birthday_Cards",
  "XYi Internal Use : XY018140, Website Updates",
  "XYi Internal Use : XY018540, Digital Housekeeping",
  "XYi Internal Use : XY019253, Studio Admin - Master Mechs Housekeeping",
  "XYi Internal Use : XY019420, XYi - Recruitment/Appraisals",
  "XYi Internal Use : XY019639, XYi - Meetings",
  "XYi Internal Use : XY019979, XYi - Office Management",
  "XYi Internal Use : XY020027, XYi - Event Planning",
  "XYi Internal Use : XY022578, XYi - Budgeting",
  "XYi Internal Use : XY022674, XYi - End of Campaign Process",
  "XYi Internal Use : XY024803, XYi - Process Development",
  "XYi Internal Use : XY025889, XYi - Angel Studios",
  "You, Me & Tuscany : XY025216, NM - Digital - Packshots - EPO",
];

export const TERRITORIES = [
  "_XYi_",
  "Albania",
  "Arabic",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Belgium",
  "Bolivia",
  "Bosnia",
  "Brazil",
  "Bulgaria",
  "Cambodia",
  "Canada",
  "Canadian-French",
  "Chile",
  "China",
  "CIS",
  "Colombia",
  "Croatia",
  "Cyprus",
  "Czech",
  "Czech Republic",
  "Denmark",
  "Domestic",
  "Dubai",
  "Ecuador",
  "Egypt",
  "Estonia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Greece",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "India - English",
  "India - Hindi",
  "India - Tamil",
  "India - Telugu",
  "Indonesia",
  "INTL - UNI",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Kazakhstan",
  "Korea",
  "Kyrgyzstan",
  "Laos",
  "Latam / Las",
  "Latvia",
  "Lebanon",
  "Lithuania",
  "Macedonia",
  "Malaysia",
  "Malta",
  "Mexico",
  "Middle East",
  "Moldova",
  "Mongolia",
  "Netherlands",
  "New Zealand",
  "Norway",
  "OV",
  "OV Suite Build",
  "Pakistan",
  "Panama",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico (Domestic)",
  "Romania",
  "Russia",
  "Serbia & Montenegro",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "Spain",
  "Spain - Catalan",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Trinidad",
  "Türkiye",
  "UK",
  "Ukraine",
  "United Arab Emirates",
  "Uruguay",
  "USA",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Yoruba (West Africa)",
];

export const TERRITORY_FLAGS = {
  _XYi_: "🏢",
  Albania: "🇦🇱",
  Arabic: "🌍",
  Argentina: "🇦🇷",
  Armenia: "🇦🇲",
  Australia: "🇦🇺",
  Austria: "🇦🇹",
  Azerbaijan: "🇦🇿",
  Belgium: "🇧🇪",
  Bolivia: "🇧🇴",
  Bosnia: "🇧🇦",
  Brazil: "🇧🇷",
  Bulgaria: "🇧🇬",
  Cambodia: "🇰🇭",
  Canada: "🇨🇦",
  "Canadian-French": "🇨🇦",
  Chile: "🇨🇱",
  China: "🇨🇳",
  CIS: "🇷🇺",
  Colombia: "🇨🇴",
  Croatia: "🇭🇷",
  Cyprus: "🇨🇾",
  Czech: "🇨🇿",
  "Czech Republic": "🇨🇿",
  Denmark: "🇩🇰",
  Domestic: "🇺🇸",
  Dubai: "🇦🇪",
  Ecuador: "🇪🇨",
  Egypt: "🇪🇬",
  Estonia: "🇪🇪",
  Finland: "🇫🇮",
  France: "🇫🇷",
  Georgia: "🇬🇪",
  Germany: "🇩🇪",
  Greece: "🇬🇷",
  "Hong Kong": "🇭🇰",
  Hungary: "🇭🇺",
  Iceland: "🇮🇸",
  India: "🇮🇳",
  "India - English": "🇮🇳",
  "India - Hindi": "🇮🇳",
  "India - Tamil": "🇮🇳",
  "India - Telugu": "🇮🇳",
  Indonesia: "🇮🇩",
  "INTL - UNI": "🌎",
  Ireland: "🇮🇪",
  Israel: "🇮🇱",
  Italy: "🇮🇹",
  Japan: "🇯🇵",
  Kazakhstan: "🇰🇿",
  Korea: "🇰🇷",
  Kyrgyzstan: "🇰🇬",
  Laos: "🇱🇦",
  "Latam / Las": "🌎",
  Latvia: "🇱🇻",
  Lebanon: "🇱🇧",
  Lithuania: "🇱🇹",
  Macedonia: "🇲🇰",
  Malaysia: "🇲🇾",
  Malta: "🇲🇹",
  Mexico: "🇲🇽",
  "Middle East": "🌍",
  Moldova: "🇲🇩",
  Mongolia: "🇲🇳",
  Netherlands: "🇳🇱",
  "New Zealand": "🇳🇿",
  Norway: "🇳🇴",
  OV: "🎬",
  "OV Suite Build": "🎞️",
  Pakistan: "🇵🇰",
  Panama: "🇵🇦",
  Paraguay: "🇵🇾",
  Peru: "🇵🇪",
  Philippines: "🇵🇭",
  Poland: "🇵🇱",
  Portugal: "🇵🇹",
  "Puerto Rico (Domestic)": "🇵🇷",
  Romania: "🇷🇴",
  Russia: "🇷🇺",
  "Serbia & Montenegro": "🇷🇸",
  Singapore: "🇸🇬",
  Slovakia: "🇸🇰",
  Slovenia: "🇸🇮",
  "South Africa": "🇿🇦",
  Spain: "🇪🇸",
  "Spain - Catalan": "🇪🇸",
  "Sri Lanka": "🇱🇰",
  Sweden: "🇸🇪",
  Switzerland: "🇨🇭",
  Taiwan: "🇹🇼",
  Thailand: "🇹🇭",
  Trinidad: "🇹🇹",
  Türkiye: "🇹🇷",
  UK: "🇬🇧",
  Ukraine: "🇺🇦",
  "United Arab Emirates": "🇦🇪",
  Uruguay: "🇺🇾",
  USA: "🇺🇸",
  Uzbekistan: "🇺🇿",
  Venezuela: "🇻🇪",
  Vietnam: "🇻🇳",
  "Yoruba (West Africa)": "🇳🇬",
};

export const CATEGORIES = [
  "Digital - Approval Site Management/Maintenance",
  "Digital - Build/Production",
  "Digital - Client Revisions/Amends",
  "Digital - Conceptualising",
  "Digital - Creating Masters",
  "Digital - Creative Approvals",
  "Digital - Flight Checking",
  "Digital - Instagram",
  "Digital - Layouts/Visualising",
  "Digital - Optimisation",
  "Digital - OV Mechanicals",
  "Digital - Packaging for Delivery",
  "Digital - Production/Localisation",
  "Digital - Project Management",
  "Digital - Project Management - Studio",
  "Digital - Proofreading",
  "Digital - Rendering",
  "Digital - Research & Development",
  "Digital - Retouching",
  "Digital - Upload/Downloading",
  "End of Campaign Process",
  "Internationalising",
  "Pitching",
  "Additional hours waiting time",
  "Budgeting",
  "Print - Client Revisions/Amends",
  "Print - Conceptualising",
  "Print - Creating Masters",
  "Print - Creative Approvals",
  "Print - Flight Checking",
  "Print - Layouts/Visualising",
  "Print - Market Created Approvals",
  "Print - OV Mechanicals",
  "Print - Packaging for Delivery",
  "Print - Production/Localisation",
  "Print - Project Management",
  "Print - Project Management - Studio",
  "Print - Proofreading",
  "Print - Research & Development",
  "Print - Retouching",
  "Print - RGB - CMYK Conversion",
  "Print - Title Rendering",
  "Print - Upload/Downloading",
  "Project Management - Translations",
  "Quoting/Estimating",
  "Watermarking",
  "XYi - Appraisals",
  "XYi - Client Meetings",
  "XYi - H&S",
  "XYi - Holiday",
  "XYi - HR",
  "XYi - IT",
  "XYi - Management Meetings",
  "XYi - Office",
  "XYi - Process Development - Client",
  "XYi - Process Development - Internal",
  "XYi - Recruitment",
  "XYi - Sick",
  "XYi - Time Off",
  "XYi - Training - Challenges",
  "XYi - Training - Demonstrations",
  "XYi - Training - External Training",
  "XYi - Training - Induction",
  "XYi - Training - Planning",
  "XYi - Training - Review",
];

export const DAYS_OF_WEEK = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
];

export const FILM_MAPPINGS = {
  ODY: "The Odyssey",
  TRM: "The Running Man",
  WK2: "Wicked II",
  DDA: "Disclosure Day",
  PP3: "Paw Patrol The Dino Movie",
  CCM: "Cocomelon The Movie",
  FID: "Forgotten Island",
  SH5: "Shrek 5",
  MO2: "The Super Mario Galaxy Movie",
  GLG: "Girls Like Girls",
  KNG: "The Comeback King",
  AB3: "Angry Birds 3",
  COBAB: "Children of Blood and Bone",
  PSGR: "Passenger",
  SF: "Street Fighter",
  TJ4: "Tad and the Magic Lamp",
  HOTB: "Heart of the Beast",
  FEM: "Finding Emily",
  SCARY: "Scary Movie 6",
  SCRY: "Scary Movie 6",
  NVC: "Novocaine",
  SB4: "Spongebob 4",
  S7: "Scream 7",
  SMRFS: "Spongebob 4",
  JA5: "Jackass 5",
  BJ4: "Bridget Jones Mad About The Boy",
  HTYD: "How To Train Your Dragon",
  JWR: "Jurassic World Rebirth",
  TR3: "Trolls 3 Band Together",
};

export const MOTION_TEAM_NAME_MAP = {
  "Antonio Burgello": "Antonio",
  "Aaron Gunasingham": "Aaron",
  "Jacqui Harrington": "Jacqui",
  "Maria Cerrato": "Maria",
  "Nicholas 😎": "Nicholas",
  "Trott ⚡️": "Luke",
  "Luke Trott": "Luke",
  Turk: "Turk",
};

export const REGION_ALIASES = {
  // Original entries
  TR: "Türkiye", CZ: "Czech Republic", CZECHIA: "Czech Republic",
  UK: "UK", UAE: "United Arab Emirates", US: "USA", ZA: "South Africa", IN: "India",
  // 2-letter ISO codes
  AE: "United Arab Emirates", AT: "Austria", AU: "Australia",
  BE: "Belgium", BR: "Brazil", CA: "Canada", CH: "Switzerland",
  CL: "Chile", CN: "China", CO: "Colombia", DE: "Germany",
  DK: "Denmark", ES: "Spain", FI: "Finland", FR: "France",
  GB: "UK", GR: "Greece", HR: "Croatia", HU: "Hungary",
  IE: "Ireland", IT: "Italy", JP: "Japan", KR: "South Korea",
  MX: "Mexico", NL: "Netherlands", NO: "Norway", NZ: "New Zealand",
  PE: "Peru", PL: "Poland", PT: "Portugal", RO: "Romania",
  RS: "Serbia", RU: "Russia", SE: "Sweden", SG: "Singapore",
  SK: "Slovakia", TH: "Thailand", TW: "Taiwan",
  // 3-letter codes common in Wrike file/task names
  POL: "Poland", GER: "Germany", SWE: "Sweden", NOR: "Norway",
  DEN: "Denmark", FIN: "Finland", AUT: "Austria", CRO: "Croatia",
  COL: "Colombia", SPA: "Spain", GRE: "Greece", POR: "Portugal",
  ITA: "Italy", FRA: "France", BEL: "Belgium", NED: "Netherlands",
  ENG: "UK", SCO: "UK", WAL: "UK",
};
